### PR TITLE
Fix duplicated timeseries in CollectorRegistry for derived metrics

### PR DESCRIPTION
**Pull request by poggenpower**
Derived metrics were created twice  and caused an exception. This change keeps track of derived metrics and make sure they won't get recreated.

I had this issue with the example config 
```
metrics:
  - name:     'mqtt_broker'
    help:     'System events from broker'
    type:     'gauge'
    topic:    '$SYS/broker/#'
    label_configs:
      - source_labels:  ['__msg_topic__']
        target_label:   '__topic__'
      - source_labels:  ['__value__']
        regex:          '^(\d+([,.]\d*)?)$|^([,.]\d+)$'
        action:         'keep'
```

and a very basic one:
```
  - name: "fhem_temperature_celsius"
    help: "443 Mhz Sensors"
    type: "gauge"
    topic: "fhem/+/temperature"
    label_configs:
      - source_labels:  ['__msg_topic__']
        target_label:   '__topic__'
```
The setup is very similar to: https://frederic-hemberger.de/notes/prometheus/monitoring-temperature-and-humidity-with-mqtt/

### CODE REVIEW

**Comment by fhemberger** [comment]
Thank you!

**Comment by eoinjordan** [comment]
I had this issue too and that fixed it

**Comment by fhemberger** [comment]
Great to hear! I currently have issues pushing the latest release as Docker image to GitHub, but it's also available on Docker Hub:
https://hub.docker.com/r/fhemberger/mqtt_exporter

**Comment by eoinj2020** [comment]
Sweet I'll check that out, and give it a test once its updated against my setup.

**Pull request merged**
